#include "Lab6/timers.h"
#include "sysctl.h"
#include "ti/devices/msp/msp.h"
#include "ti/devices/msp/m0p/mspm0g350x.h"
#include "ti/devices/msp/peripherals/hw_gptimer.h" 

static uint32_t PWMA0timclk = 0;
static uint32_t PWMA1timclk = 0;
void TIMG0_init(uint32_t period, uint32_t prescaler){
	if (!(TIMG0->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
        TIMG0->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETSTKYCLR_CLR | GPTIMER_RSTCTL_RESETASSERT_ASSERT);
        TIMG0->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W | GPTIMER_PWREN_ENABLE_ENABLE);
    }
    
		uint32_t freq = SYSCTL_SYSCLK_getULPCLK();
		uint32_t timclk = freq/((period) * (prescaler));
		
		TIMG0->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_MASK;
		TIMG0->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
		TIMG0->COMMONREGS.CPS |= prescaler - 1;
		TIMG0->COUNTERREGS.LOAD = timclk - 1;
		
		TIMG0->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_EN_ENABLED|GPTIMER_CTRCTL_CM_DOWN|
		GPTIMER_CTRCTL_CVAE_LDVAL|GPTIMER_CTRCTL_REPEAT_REPEAT_1);
		
		
		TIMG0->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		TIMG6->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK;
		
		__disable_irq();
		
		TIMG0-> CPU_INT.ICLR = GPTIMER_GEN_EVENT1_ICLR_Z_CLR; 
		TIMG0-> CPU_INT.IMASK = GPTIMER_GEN_EVENT0_IMASK_Z_SET;
		
		NVIC_EnableIRQ(TIMG0_INT_IRQn);
		__enable_irq();

}


/**
 * @brief Timer G6 module initialization. General purpose timer
*/
void TIMG6_init(uint32_t period, uint32_t prescaler){
	 if (!(TIMG6->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
        TIMG6->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETSTKYCLR_CLR | GPTIMER_RSTCTL_RESETASSERT_ASSERT);
        TIMG6->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W | GPTIMER_PWREN_ENABLE_ENABLE);
			}
		uint32_t freq = SYSCTL_SYSCLK_getMCLK();
		uint32_t timclk = freq/((period) * (prescaler));
			
		TIMG6->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_MASK;
		TIMG6->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
    TIMG6->COMMONREGS.CPS |= prescaler - 1;
		TIMG6->COUNTERREGS.LOAD = timclk - 1;
		
		TIMG6->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_CM_DOWN| GPTIMER_CTRCTL_CVAE_LDVAL|
		GPTIMER_CTRCTL_REPEAT_REPEAT_1| GPTIMER_CTRCTL_EN_ENABLED);
		
		TIMG6->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		TIMG6->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK;
			
		__disable_irq();
		
		TIMG6-> CPU_INT.ICLR = GPTIMER_CPU_INT_ICLR_Z_CLR; 
		TIMG6-> CPU_INT.IMASK = GPTIMER_CPU_INT_IMASK_Z_SET;
		
		NVIC_EnableIRQ(TIMG6_INT_IRQn);
		__enable_irq();
}


/**
 * @brief Timer G12 module initialization. General purpose timer
 * @note Timer G12 has no prescaler
*/
void TIMG12_init(uint32_t period){
	if (!(TIMG12->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
				TIMG12->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETASSERT_ASSERT);
        TIMG12->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W  | GPTIMER_PWREN_ENABLE_ENABLE);
    }
	
		uint32_t freq = SYSCTL_SYSCLK_getMCLK();
		uint32_t timclk = freq/period;
		
		TIMG12->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_MASK;
		TIMG12->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
		TIMG12->COUNTERREGS.LOAD = timclk - 1;
		
		TIMG12->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_CM_DOWN| GPTIMER_CTRCTL_CVAE_LDVAL|
		GPTIMER_CTRCTL_REPEAT_REPEAT_1| GPTIMER_CTRCTL_EN_ENABLED);

		TIMG12->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		TIMG12->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK;
		
		__disable_irq();
		
		TIMG12-> CPU_INT.ICLR = GPTIMER_CPU_INT_ICLR_Z_CLR; 
		TIMG12-> CPU_INT.IMASK = GPTIMER_CPU_INT_IMASK_Z_SET;
		
		NVIC_EnableIRQ(TIMG12_INT_IRQn);
		__enable_irq();
}

/**
* TIMA0   Channel 0  DC Motor    PB8   PINCM25
* TIMA0   Channel 1  DC Motor    PB12  PINCM29
* TIMA0   Channel 2  DC Motor    PB17  PINCM43
* TIMA0   Channel 3  DC Motor    PB13  PINCM30
*/

void TIMA0_PWM_init(uint8_t pin, uint32_t period, uint32_t prescaler, double percentDutyCycle){
	//A.
	if (!(TIMA0->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
				TIMA0->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETASSERT_ASSERT |GPTIMER_RSTCTL_RESETSTKYCLR_CLR);
        TIMA0->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W  | GPTIMER_PWREN_ENABLE_ENABLE);
    }
		TIMA0->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_ENABLE;
		TIMA0->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
		TIMA0->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		
		uint32_t freq = SYSCTL_SYSCLK_getMCLK();
		PWMA0timclk = freq/((period) * (prescaler));
		TIMA0->COMMONREGS.CPS |= prescaler - 1;
		TIMA0->COUNTERREGS.LOAD = PWMA0timclk - 1;
		TIMA0->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_CM_DOWN| GPTIMER_CTRCTL_CVAE_LDVAL|
		GPTIMER_CTRCTL_REPEAT_REPEAT_1);
		uint32_t dutyValue = (uint32_t)(PWMA0timclk * percentDutyCycle);
		TIMA0->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK; 
		//B and C
		switch(pin){
			case 0: // channels
				IOMUX->SECCFG.PINCM[IOMUX_PINCM25]|= ( IOMUX_PINCM_PC_CONNECTED | 0x01 ); // PF and PC set
				GPIOB->DOESET31_0 |= GPIO_DOESET31_0_DIO8_SET; // GPIO output enable
				// Reasoning for 01[0] choice: Channel 0
				TIMA0->COUNTERREGS.CC_01[0] = dutyValue;
				TIMA0->COUNTERREGS.CCCTL_01[0] = GPTIMER_CCCTL_01_COC_CAPTURE;
				TIMA0->COMMONREGS.CCPD = GPTIMER_CCPD_C0CCP0_OUTPUT;
				TIMA0->COUNTERREGS.CCACT_01[0] = (GPTIMER_CCACT_01_CDACT_CCP_LOW|GPTIMER_CCACT_01_LACT_CCP_HIGH);
				TIMA0->COUNTERREGS.OCTL_01[0] = (GPTIMER_OCTL_01_CCPO_FUNCVAL|GPTIMER_OCTL_01_CCPOINV_NOINV
				|GPTIMER_OCTL_01_CCPIV_LOW);
				TIMA0->COMMONREGS.ODIS = GPTIMER_ODIS_C0CCP0_CCP_OUTPUT_LOW;
				break;
			case 1:
				IOMUX->SECCFG.PINCM[IOMUX_PINCM29]|= ( IOMUX_PINCM_PC_CONNECTED | 0x01 ); // PF and PC set
				GPIOB->DOESET31_0 |= GPIO_DOESET31_0_DIO12_SET; // GPIO output enable
				TIMA0->COUNTERREGS.CC_01[1] = dutyValue;
				TIMA0->COUNTERREGS.CCCTL_01[1] = GPTIMER_CCCTL_01_COC_CAPTURE;
				TIMA0->COMMONREGS.CCPD = GPTIMER_CCPD_C0CCP1_OUTPUT;
				TIMA0->COUNTERREGS.CCACT_01[1] = (GPTIMER_CCACT_01_CDACT_CCP_LOW|GPTIMER_CCACT_01_LACT_CCP_HIGH);
				TIMA0->COUNTERREGS.OCTL_01[1] = (GPTIMER_OCTL_01_CCPO_FUNCVAL|GPTIMER_OCTL_01_CCPOINV_NOINV
				|GPTIMER_OCTL_01_CCPIV_LOW);
				TIMA0->COMMONREGS.ODIS = GPTIMER_ODIS_C0CCP1_CCP_OUTPUT_LOW;
				break;
			case 2:
				IOMUX->SECCFG.PINCM[IOMUX_PINCM43]|= ( IOMUX_PINCM_PC_CONNECTED | 0x01 ); // PF and PC set
				GPIOB->DOESET31_0 |= GPIO_DOESET31_0_DIO17_SET; // GPIO output enable
				TIMA0->COUNTERREGS.CC_23[0] = dutyValue;
				TIMA0->COUNTERREGS.CCCTL_23[0] = GPTIMER_CCCTL_23_COC_CAPTURE;
				TIMA0->COMMONREGS.CCPD = GPTIMER_CCPD_C0CCP2_OUTPUT;
				TIMA0->COUNTERREGS.CCACT_23[0] = (GPTIMER_CCACT_23_CDACT_CCP_LOW|GPTIMER_CCACT_23_LACT_CCP_HIGH);
				TIMA0->COUNTERREGS.OCTL_23[0] = (GPTIMER_OCTL_23_CCPO_FUNCVAL|GPTIMER_OCTL_23_CCPOINV_NOINV
				|GPTIMER_OCTL_23_CCPIV_LOW);
				TIMA0->COMMONREGS.ODIS = GPTIMER_ODIS_C0CCP2_CCP_OUTPUT_LOW;
				break;
			case 3:
				IOMUX->SECCFG.PINCM[IOMUX_PINCM30]|= ( IOMUX_PINCM_PC_CONNECTED | 0x01 ); // PF and PC set
				GPIOB->DOESET31_0 |= GPIO_DOESET31_0_DIO13_SET; // GPIO output enable
				TIMA0->COUNTERREGS.CC_23[1] = dutyValue;
				TIMA0->COUNTERREGS.CCCTL_23[1] = GPTIMER_CCCTL_23_COC_CAPTURE;
				TIMA0->COMMONREGS.CCPD = GPTIMER_CCPD_C0CCP3_OUTPUT;
				TIMA0->COUNTERREGS.CCACT_23[1] = (GPTIMER_CCACT_23_CDACT_CCP_LOW|GPTIMER_CCACT_23_LACT_CCP_HIGH);
				TIMA0->COUNTERREGS.OCTL_23[1] = (GPTIMER_OCTL_23_CCPO_FUNCVAL|GPTIMER_OCTL_23_CCPOINV_NOINV
				|GPTIMER_OCTL_23_CCPIV_LOW);
				TIMA0->COMMONREGS.ODIS = GPTIMER_ODIS_C0CCP3_CCP_OUTPUT_LOW;
				break;
		}		
		TIMA0->COUNTERREGS.CTRCTL = GPTIMER_CTRCTL_EN_ENABLED;
}

/**
 * @brief Timer A1 module PWM initialization
 * @param[in] pin - Timer PWM output pin / channel
 * @param[in] period - Timer load value
 * @param[in] prescaler - Timer prescale value
 * @param[in] percenetDutyCycle - PWM duty cycle positive
 * @note Store period to be able to adjust duty cycle percentage later
* TIMA1   Channel 0   Servo Motor   PB4  PINCM17
*/
void TIMA1_PWM_init(uint8_t pin, uint32_t period, uint32_t prescaler, double percentDutyCycle){	 
	if (!(TIMA1->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
				TIMA1->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETASSERT_ASSERT |GPTIMER_RSTCTL_RESETSTKYCLR_CLR);
        TIMA1->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W  | GPTIMER_PWREN_ENABLE_ENABLE);
    }
		TIMA1->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_ENABLE;
		TIMA1->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
		TIMA1->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		
		uint32_t freq = SYSCTL_SYSCLK_getMCLK();
		PWMA1timclk = freq/((period) * (prescaler));
		TIMA1->COMMONREGS.CPS |= prescaler - 1;
		TIMA1->COUNTERREGS.LOAD = PWMA1timclk - 1;
		TIMA1->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_CM_DOWN| GPTIMER_CTRCTL_CVAE_LDVAL|
		GPTIMER_CTRCTL_REPEAT_REPEAT_1);
		uint32_t dutyValue = (uint32_t)(PWMA1timclk * percentDutyCycle);
		TIMA1->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK; 
		switch(pin){
			case 0:
				IOMUX->SECCFG.PINCM[IOMUX_PINCM17]|= ( IOMUX_PINCM_PC_CONNECTED | 0x01 ); // PF and PC set
				GPIOB->DOESET31_0 |= GPIO_DOESET31_0_DIO4_SET; // GPIO output enable
				// Reasoning for 01[0] choice: Channel 0
				TIMA1->COUNTERREGS.CC_01[0] = dutyValue;
				TIMA1->COUNTERREGS.CCCTL_01[0] = GPTIMER_CCCTL_01_COC_CAPTURE;
				TIMA1->COMMONREGS.CCPD = GPTIMER_CCPD_C0CCP0_OUTPUT;
				TIMA1->COUNTERREGS.CCACT_01[0] = (GPTIMER_CCACT_01_CDACT_CCP_LOW|GPTIMER_CCACT_01_LACT_CCP_HIGH);
				TIMA1->COUNTERREGS.OCTL_01[0] = (GPTIMER_OCTL_01_CCPO_FUNCVAL|GPTIMER_OCTL_01_CCPOINV_NOINV
				|GPTIMER_OCTL_01_CCPIV_LOW);
				TIMA1->COMMONREGS.ODIS = GPTIMER_ODIS_C0CCP0_CCP_OUTPUT_LOW;
				break;
		}
		TIMA1->COUNTERREGS.CTRCTL = GPTIMER_CTRCTL_EN_ENABLED;
}


/**
 * @brief Change PWM duty cycle for all Timer A0 channels
 * @param[in] pin - Timer PWM output pin / channel
 * @param[in] percentDutyCycle - Duty cycle to change to
*/
void TIMA0_PWM_DutyCycle(uint8_t pin, double percentDutyCycle){
	
	uint32_t dutyValue = (uint32_t)(PWMA0timclk * percentDutyCycle);
	
	switch(pin){
			case 0:
				TIMA0->COUNTERREGS.CC_01[0] = dutyValue;
				break;
			case 1:
				TIMA0->COUNTERREGS.CC_01[1] = dutyValue;
				break;
			case 2:
				TIMA0->COUNTERREGS.CC_23[0] = dutyValue;
				break;
			case 3:
				TIMA0->COUNTERREGS.CC_23[1] = dutyValue;
				break;
		}
}


/**
 * @brief Change PWM duty cycle for all Timer A1 channels
 * @param[in] pin - Timer PWM output pin / channel
 * @param[in] percentDutyCycle - Duty cycle to change to
*/
void TIMA1_PWM_DutyCycle(uint8_t pin, double percentDutyCycle){
	uint32_t dutyValue = (uint32_t)(PWMA1timclk * percentDutyCycle);
	switch(pin){
			case 0:
				TIMA1->COUNTERREGS.CC_01[0] = dutyValue;
				break;
		}
}




