
#include "timers.h"
#include "sysctl.h"
#include "ti/devices/msp/msp.h"
#include "ti/devices/msp/m0p/mspm0g350x.h"
#include "ti/devices/msp/peripherals/hw_gptimer.h" 

void TIMG0_init(uint32_t period, uint32_t prescaler){
	if (!(TIMG0->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
        TIMG0->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETSTKYCLR_CLR | GPTIMER_RSTCTL_RESETASSERT_ASSERT);
        TIMG0->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W | GPTIMER_PWREN_ENABLE_ENABLE);
    }
    
		uint32_t freq = SYSCTL_SYSCLK_getULPCLK();
		uint32_t timclk = freq/((period) * (prescaler));
		
		TIMG0->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_MASK;
		TIMG0->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
		TIMG0->COMMONREGS.CPS |= prescaler - 1;
		TIMG0->COUNTERREGS.LOAD = timclk - 1;
		
		TIMG0->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_EN_ENABLED|GPTIMER_CTRCTL_CM_DOWN|
		GPTIMER_CTRCTL_CVAE_LDVAL|GPTIMER_CTRCTL_REPEAT_REPEAT_1);
		
		
		TIMG0->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		TIMG6->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK;
		
		__disable_irq();
		
		TIMG0-> CPU_INT.ICLR = GPTIMER_GEN_EVENT1_ICLR_Z_CLR; 
		TIMG0-> CPU_INT.IMASK = GPTIMER_GEN_EVENT0_IMASK_Z_SET;
		
		NVIC_EnableIRQ(TIMG0_INT_IRQn);
		__enable_irq();

}


/**
 * @brief Timer G6 module initialization. General purpose timer
*/
void TIMG6_init(uint32_t period, uint32_t prescaler){
	 if (!(TIMG6->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
        TIMG6->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETSTKYCLR_CLR | GPTIMER_RSTCTL_RESETASSERT_ASSERT);
        TIMG6->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W | GPTIMER_PWREN_ENABLE_ENABLE);
			}
		uint32_t freq = SYSCTL_SYSCLK_getMCLK();
		uint32_t timclk = freq/((period) * (prescaler));
			
		TIMG6->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_MASK;
		TIMG6->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
    TIMG6->COMMONREGS.CPS |= prescaler - 1;
		TIMG6->COUNTERREGS.LOAD = timclk - 1;
		
		TIMG6->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_CM_DOWN| GPTIMER_CTRCTL_CVAE_LDVAL|
		GPTIMER_CTRCTL_REPEAT_REPEAT_1| GPTIMER_CTRCTL_EN_ENABLED);
		
		TIMG6->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		TIMG6->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK;
			
		__disable_irq();
		
		TIMG6-> CPU_INT.ICLR = GPTIMER_CPU_INT_ICLR_Z_CLR; 
		TIMG6-> CPU_INT.IMASK = GPTIMER_CPU_INT_IMASK_Z_SET;
		
		NVIC_EnableIRQ(TIMG6_INT_IRQn);
		__enable_irq();
}


/**
 * @brief Timer G12 module initialization. General purpose timer
 * @note Timer G12 has no prescaler
*/
void TIMG12_init(uint32_t period){
	if (!(TIMG12->GPRCM.PWREN & GPTIMER_PWREN_ENABLE_MASK)) {
				TIMG12->GPRCM.RSTCTL = (GPTIMER_RSTCTL_KEY_UNLOCK_W | GPTIMER_RSTCTL_RESETASSERT_ASSERT);
        TIMG12->GPRCM.PWREN = (GPTIMER_PWREN_KEY_UNLOCK_W  | GPTIMER_PWREN_ENABLE_ENABLE);
    }
	
		uint32_t freq = SYSCTL_SYSCLK_getMCLK();
		uint32_t timclk = freq/period;
		
		TIMG12->CLKSEL |= GPTIMER_CLKSEL_BUSCLK_SEL_MASK;
		TIMG12->CLKDIV |= GPTIMER_CLKDIV_RATIO_DIV_BY_1;
		TIMG12->COUNTERREGS.LOAD = timclk - 1;
		
		TIMG12->COUNTERREGS.CTRCTL = (GPTIMER_CTRCTL_CM_DOWN| GPTIMER_CTRCTL_CVAE_LDVAL|
		GPTIMER_CTRCTL_REPEAT_REPEAT_1| GPTIMER_CTRCTL_EN_ENABLED);

		TIMG12->COMMONREGS.CCLKCTL = GPTIMER_CCLKCTL_CLKEN_ENABLED;
		TIMG12->COUNTERREGS.CTRCTL &= ~GPTIMER_CTRCTL_EN_MASK;
		
		__disable_irq();
		
		TIMG12-> CPU_INT.ICLR = GPTIMER_CPU_INT_ICLR_Z_CLR; 
		TIMG12-> CPU_INT.IMASK = GPTIMER_CPU_INT_IMASK_Z_SET;
		
		NVIC_EnableIRQ(TIMG12_INT_IRQn);
		__enable_irq();
}
